<?php

/**
 * @file
 * Hook implementations for ucsf_onetrust module.
 */

/**
 * Implements hook_page_attachments().
 */
function ucsf_onetrust_page_attachments(array &$attachments) {
 
    if (\Drupal::service('router.admin_context')->isAdminRoute()) {
      return;
    }
    //  $_ENV['PANTHEON_ENVIRONMENT']=='live' for pantheon support in the future
    if (isset($_ENV['AH_PRODUCTION'])) {
      $src = 'https://cdn.cookielaw.org/consent/69de606f-159b-41ad-82da-d7a76950873b/OtAutoBlock.js';
      $idcode = '69de606f-159b-41ad-82da-d7a76950873b';
    } else {
      $src = 'https://cdn.cookielaw.org/consent/69de606f-159b-41ad-82da-d7a76950873b-test/OtAutoBlock.js';
      $idcode = '69de606f-159b-41ad-82da-d7a76950873b-test';
    }


    $attachments['#attached']['library'][] = 'ucsf_onetrust/ucsf_onetrust';

    $attachments['#attached']['html_head'][] = [
      [
        '#type' => 'html_tag',
        '#tag' => 'script',
        '#attributes' => ['src' => $src],
      ],
      'OtAutoBlock',
    ];

    $attachments['#attached']['html_head'][] = [
      [
        '#type' => 'html_tag',
        '#tag' => 'script',
        '#attributes' => [
          'src' => 'https://cdn.cookielaw.org/scripttemplates/otSDKStub.js',
          'charset' => 'UTF-8',
          'data-domain-script' => $idcode
        ],
      ],
      'otSDKStub',
    ];
    
    $attachments['#attached']['html_head'][] = [
      [
        '#type' => 'html_tag',
        '#tag' => 'script',
        '#value' => 'function OptanonWrapper() {
          // Check if banner div is available
          if (document.getElementById("onetrust-banner-sdk")) {
            // Get the buttons and container
            var acceptBtn = document.getElementById("onetrust-accept-btn-handler");
            var declineBtn = document.getElementById("onetrust-reject-all-handler");
            var cookieSettingsBtn = document.getElementById("onetrust-pc-btn-handler");
            var btnContainer = document.getElementById("onetrust-button-group");
            
            btnContainer.append(acceptBtn, cookieSettingsBtn, declineBtn);
          }
        }',
      ],
      'OptanonWrapper',
    ];

}
